modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/JustDoom/MelonPants/issues"
license = "MIT"

[[mods]]
modId = "melonpants"
version = "${version}"
displayName = "Melon Pants"
authors = "JustDoom (Developer), SlyFox (Artist)"
description = '''
When life gives you melons, make melon pants!
'''
#logoFile = ""

[[dependencies.melonpants]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.melonpants]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.melonpants]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"